export const FETCHING_INITIAL_EXPENSES = "FETCHING_INITIAL_EXPENSES";

export const FETCH_EXPENSE_ID = "FETCH_EXPENSE_ID";

export const SAVE = "SAVE";

export const UPDATE = "UPDATE";
export const UPDATE_FAILED = "UPDATE_FAILED";

export const DELETE = "DELETE";

export const FETCHED_SUCCESS = "FETCHED_SUCCESS"; 
export const FETCHED_DETAILS_SUCCESS = "FETCHED_DETAILS_SUCCESS"; 
export const FAILED = "FAILED";

